# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(CMAKE_COMMAND) -E cmake_progress_start "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build/CMakeFiles" "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build/tmc3/CMakeFiles/progress.marks"
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f CMakeFiles/Makefile2 tmc3/all
	$(CMAKE_COMMAND) -E cmake_progress_start "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f CMakeFiles/Makefile2 tmc3/clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f CMakeFiles/Makefile2 tmc3/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f CMakeFiles/Makefile2 tmc3/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
tmc3/CMakeFiles/ply-merge.dir/rule:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f CMakeFiles/Makefile2 tmc3/CMakeFiles/ply-merge.dir/rule
.PHONY : tmc3/CMakeFiles/ply-merge.dir/rule

# Convenience name for target.
ply-merge: tmc3/CMakeFiles/ply-merge.dir/rule

.PHONY : ply-merge

# fast build rule for target.
ply-merge/fast:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/build
.PHONY : ply-merge/fast

# Convenience name for target.
tmc3/CMakeFiles/tmc3.dir/rule:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f CMakeFiles/Makefile2 tmc3/CMakeFiles/tmc3.dir/rule
.PHONY : tmc3/CMakeFiles/tmc3.dir/rule

# Convenience name for target.
tmc3: tmc3/CMakeFiles/tmc3.dir/rule

.PHONY : tmc3

# fast build rule for target.
tmc3/fast:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/build
.PHONY : tmc3/fast

# Convenience name for target.
tmc3/CMakeFiles/genversion.dir/rule:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f CMakeFiles/Makefile2 tmc3/CMakeFiles/genversion.dir/rule
.PHONY : tmc3/CMakeFiles/genversion.dir/rule

# Convenience name for target.
genversion: tmc3/CMakeFiles/genversion.dir/rule

.PHONY : genversion

# fast build rule for target.
genversion/fast:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/genversion.dir/build.make tmc3/CMakeFiles/genversion.dir/build
.PHONY : genversion/fast

AttributeCommon.o: AttributeCommon.cpp.o

.PHONY : AttributeCommon.o

# target to build an object file
AttributeCommon.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/AttributeCommon.cpp.o
.PHONY : AttributeCommon.cpp.o

AttributeCommon.i: AttributeCommon.cpp.i

.PHONY : AttributeCommon.i

# target to preprocess a source file
AttributeCommon.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/AttributeCommon.cpp.i
.PHONY : AttributeCommon.cpp.i

AttributeCommon.s: AttributeCommon.cpp.s

.PHONY : AttributeCommon.s

# target to generate assembly for a file
AttributeCommon.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/AttributeCommon.cpp.s
.PHONY : AttributeCommon.cpp.s

AttributeDecoder.o: AttributeDecoder.cpp.o

.PHONY : AttributeDecoder.o

# target to build an object file
AttributeDecoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/AttributeDecoder.cpp.o
.PHONY : AttributeDecoder.cpp.o

AttributeDecoder.i: AttributeDecoder.cpp.i

.PHONY : AttributeDecoder.i

# target to preprocess a source file
AttributeDecoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/AttributeDecoder.cpp.i
.PHONY : AttributeDecoder.cpp.i

AttributeDecoder.s: AttributeDecoder.cpp.s

.PHONY : AttributeDecoder.s

# target to generate assembly for a file
AttributeDecoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/AttributeDecoder.cpp.s
.PHONY : AttributeDecoder.cpp.s

AttributeEncoder.o: AttributeEncoder.cpp.o

.PHONY : AttributeEncoder.o

# target to build an object file
AttributeEncoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/AttributeEncoder.cpp.o
.PHONY : AttributeEncoder.cpp.o

AttributeEncoder.i: AttributeEncoder.cpp.i

.PHONY : AttributeEncoder.i

# target to preprocess a source file
AttributeEncoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/AttributeEncoder.cpp.i
.PHONY : AttributeEncoder.cpp.i

AttributeEncoder.s: AttributeEncoder.cpp.s

.PHONY : AttributeEncoder.s

# target to generate assembly for a file
AttributeEncoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/AttributeEncoder.cpp.s
.PHONY : AttributeEncoder.cpp.s

DualLutCoder.o: DualLutCoder.cpp.o

.PHONY : DualLutCoder.o

# target to build an object file
DualLutCoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/DualLutCoder.cpp.o
.PHONY : DualLutCoder.cpp.o

DualLutCoder.i: DualLutCoder.cpp.i

.PHONY : DualLutCoder.i

# target to preprocess a source file
DualLutCoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/DualLutCoder.cpp.i
.PHONY : DualLutCoder.cpp.i

DualLutCoder.s: DualLutCoder.cpp.s

.PHONY : DualLutCoder.s

# target to generate assembly for a file
DualLutCoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/DualLutCoder.cpp.s
.PHONY : DualLutCoder.cpp.s

FixedPoint.o: FixedPoint.cpp.o

.PHONY : FixedPoint.o

# target to build an object file
FixedPoint.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/FixedPoint.cpp.o
.PHONY : FixedPoint.cpp.o

FixedPoint.i: FixedPoint.cpp.i

.PHONY : FixedPoint.i

# target to preprocess a source file
FixedPoint.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/FixedPoint.cpp.i
.PHONY : FixedPoint.cpp.i

FixedPoint.s: FixedPoint.cpp.s

.PHONY : FixedPoint.s

# target to generate assembly for a file
FixedPoint.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/FixedPoint.cpp.s
.PHONY : FixedPoint.cpp.s

OctreeNeighMap.o: OctreeNeighMap.cpp.o

.PHONY : OctreeNeighMap.o

# target to build an object file
OctreeNeighMap.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/OctreeNeighMap.cpp.o
.PHONY : OctreeNeighMap.cpp.o

OctreeNeighMap.i: OctreeNeighMap.cpp.i

.PHONY : OctreeNeighMap.i

# target to preprocess a source file
OctreeNeighMap.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/OctreeNeighMap.cpp.i
.PHONY : OctreeNeighMap.cpp.i

OctreeNeighMap.s: OctreeNeighMap.cpp.s

.PHONY : OctreeNeighMap.s

# target to generate assembly for a file
OctreeNeighMap.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/OctreeNeighMap.cpp.s
.PHONY : OctreeNeighMap.cpp.s

RAHT.o: RAHT.cpp.o

.PHONY : RAHT.o

# target to build an object file
RAHT.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/RAHT.cpp.o
.PHONY : RAHT.cpp.o

RAHT.i: RAHT.cpp.i

.PHONY : RAHT.i

# target to preprocess a source file
RAHT.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/RAHT.cpp.i
.PHONY : RAHT.cpp.i

RAHT.s: RAHT.cpp.s

.PHONY : RAHT.s

# target to generate assembly for a file
RAHT.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/RAHT.cpp.s
.PHONY : RAHT.cpp.s

TMC3.o: TMC3.cpp.o

.PHONY : TMC3.o

# target to build an object file
TMC3.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/TMC3.cpp.o
.PHONY : TMC3.cpp.o

TMC3.i: TMC3.cpp.i

.PHONY : TMC3.i

# target to preprocess a source file
TMC3.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/TMC3.cpp.i
.PHONY : TMC3.cpp.i

TMC3.s: TMC3.cpp.s

.PHONY : TMC3.s

# target to generate assembly for a file
TMC3.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/TMC3.cpp.s
.PHONY : TMC3.cpp.s

__/dependencies/program-options-lite/program_options_lite.o: __/dependencies/program-options-lite/program_options_lite.cpp.o

.PHONY : __/dependencies/program-options-lite/program_options_lite.o

# target to build an object file
__/dependencies/program-options-lite/program_options_lite.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/__/dependencies/program-options-lite/program_options_lite.cpp.o
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/__/dependencies/program-options-lite/program_options_lite.cpp.o
.PHONY : __/dependencies/program-options-lite/program_options_lite.cpp.o

__/dependencies/program-options-lite/program_options_lite.i: __/dependencies/program-options-lite/program_options_lite.cpp.i

.PHONY : __/dependencies/program-options-lite/program_options_lite.i

# target to preprocess a source file
__/dependencies/program-options-lite/program_options_lite.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/__/dependencies/program-options-lite/program_options_lite.cpp.i
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/__/dependencies/program-options-lite/program_options_lite.cpp.i
.PHONY : __/dependencies/program-options-lite/program_options_lite.cpp.i

__/dependencies/program-options-lite/program_options_lite.s: __/dependencies/program-options-lite/program_options_lite.cpp.s

.PHONY : __/dependencies/program-options-lite/program_options_lite.s

# target to generate assembly for a file
__/dependencies/program-options-lite/program_options_lite.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/__/dependencies/program-options-lite/program_options_lite.cpp.s
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/__/dependencies/program-options-lite/program_options_lite.cpp.s
.PHONY : __/dependencies/program-options-lite/program_options_lite.cpp.s

__/dependencies/schroedinger/schroarith.o: __/dependencies/schroedinger/schroarith.c.o

.PHONY : __/dependencies/schroedinger/schroarith.o

# target to build an object file
__/dependencies/schroedinger/schroarith.c.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/__/dependencies/schroedinger/schroarith.c.o
.PHONY : __/dependencies/schroedinger/schroarith.c.o

__/dependencies/schroedinger/schroarith.i: __/dependencies/schroedinger/schroarith.c.i

.PHONY : __/dependencies/schroedinger/schroarith.i

# target to preprocess a source file
__/dependencies/schroedinger/schroarith.c.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/__/dependencies/schroedinger/schroarith.c.i
.PHONY : __/dependencies/schroedinger/schroarith.c.i

__/dependencies/schroedinger/schroarith.s: __/dependencies/schroedinger/schroarith.c.s

.PHONY : __/dependencies/schroedinger/schroarith.s

# target to generate assembly for a file
__/dependencies/schroedinger/schroarith.c.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/__/dependencies/schroedinger/schroarith.c.s
.PHONY : __/dependencies/schroedinger/schroarith.c.s

__/tools/ply-merge.o: __/tools/ply-merge.cpp.o

.PHONY : __/tools/ply-merge.o

# target to build an object file
__/tools/ply-merge.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/__/tools/ply-merge.cpp.o
.PHONY : __/tools/ply-merge.cpp.o

__/tools/ply-merge.i: __/tools/ply-merge.cpp.i

.PHONY : __/tools/ply-merge.i

# target to preprocess a source file
__/tools/ply-merge.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/__/tools/ply-merge.cpp.i
.PHONY : __/tools/ply-merge.cpp.i

__/tools/ply-merge.s: __/tools/ply-merge.cpp.s

.PHONY : __/tools/ply-merge.s

# target to generate assembly for a file
__/tools/ply-merge.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/__/tools/ply-merge.cpp.s
.PHONY : __/tools/ply-merge.cpp.s

attribute_raw_decoder.o: attribute_raw_decoder.cpp.o

.PHONY : attribute_raw_decoder.o

# target to build an object file
attribute_raw_decoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/attribute_raw_decoder.cpp.o
.PHONY : attribute_raw_decoder.cpp.o

attribute_raw_decoder.i: attribute_raw_decoder.cpp.i

.PHONY : attribute_raw_decoder.i

# target to preprocess a source file
attribute_raw_decoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/attribute_raw_decoder.cpp.i
.PHONY : attribute_raw_decoder.cpp.i

attribute_raw_decoder.s: attribute_raw_decoder.cpp.s

.PHONY : attribute_raw_decoder.s

# target to generate assembly for a file
attribute_raw_decoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/attribute_raw_decoder.cpp.s
.PHONY : attribute_raw_decoder.cpp.s

attribute_raw_encoder.o: attribute_raw_encoder.cpp.o

.PHONY : attribute_raw_encoder.o

# target to build an object file
attribute_raw_encoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/attribute_raw_encoder.cpp.o
.PHONY : attribute_raw_encoder.cpp.o

attribute_raw_encoder.i: attribute_raw_encoder.cpp.i

.PHONY : attribute_raw_encoder.i

# target to preprocess a source file
attribute_raw_encoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/attribute_raw_encoder.cpp.i
.PHONY : attribute_raw_encoder.cpp.i

attribute_raw_encoder.s: attribute_raw_encoder.cpp.s

.PHONY : attribute_raw_encoder.s

# target to generate assembly for a file
attribute_raw_encoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/attribute_raw_encoder.cpp.s
.PHONY : attribute_raw_encoder.cpp.s

coordinate_conversion.o: coordinate_conversion.cpp.o

.PHONY : coordinate_conversion.o

# target to build an object file
coordinate_conversion.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/coordinate_conversion.cpp.o
.PHONY : coordinate_conversion.cpp.o

coordinate_conversion.i: coordinate_conversion.cpp.i

.PHONY : coordinate_conversion.i

# target to preprocess a source file
coordinate_conversion.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/coordinate_conversion.cpp.i
.PHONY : coordinate_conversion.cpp.i

coordinate_conversion.s: coordinate_conversion.cpp.s

.PHONY : coordinate_conversion.s

# target to generate assembly for a file
coordinate_conversion.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/coordinate_conversion.cpp.s
.PHONY : coordinate_conversion.cpp.s

decoder.o: decoder.cpp.o

.PHONY : decoder.o

# target to build an object file
decoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/decoder.cpp.o
.PHONY : decoder.cpp.o

decoder.i: decoder.cpp.i

.PHONY : decoder.i

# target to preprocess a source file
decoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/decoder.cpp.i
.PHONY : decoder.cpp.i

decoder.s: decoder.cpp.s

.PHONY : decoder.s

# target to generate assembly for a file
decoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/decoder.cpp.s
.PHONY : decoder.cpp.s

encoder.o: encoder.cpp.o

.PHONY : encoder.o

# target to build an object file
encoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/encoder.cpp.o
.PHONY : encoder.cpp.o

encoder.i: encoder.cpp.i

.PHONY : encoder.i

# target to preprocess a source file
encoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/encoder.cpp.i
.PHONY : encoder.cpp.i

encoder.s: encoder.cpp.s

.PHONY : encoder.s

# target to generate assembly for a file
encoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/encoder.cpp.s
.PHONY : encoder.cpp.s

entropydirac.o: entropydirac.cpp.o

.PHONY : entropydirac.o

# target to build an object file
entropydirac.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/entropydirac.cpp.o
.PHONY : entropydirac.cpp.o

entropydirac.i: entropydirac.cpp.i

.PHONY : entropydirac.i

# target to preprocess a source file
entropydirac.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/entropydirac.cpp.i
.PHONY : entropydirac.cpp.i

entropydirac.s: entropydirac.cpp.s

.PHONY : entropydirac.s

# target to generate assembly for a file
entropydirac.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/entropydirac.cpp.s
.PHONY : entropydirac.cpp.s

frame.o: frame.cpp.o

.PHONY : frame.o

# target to build an object file
frame.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/frame.cpp.o
.PHONY : frame.cpp.o

frame.i: frame.cpp.i

.PHONY : frame.i

# target to preprocess a source file
frame.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/frame.cpp.i
.PHONY : frame.cpp.i

frame.s: frame.cpp.s

.PHONY : frame.s

# target to generate assembly for a file
frame.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/frame.cpp.s
.PHONY : frame.cpp.s

geometry_intra_pred.o: geometry_intra_pred.cpp.o

.PHONY : geometry_intra_pred.o

# target to build an object file
geometry_intra_pred.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_intra_pred.cpp.o
.PHONY : geometry_intra_pred.cpp.o

geometry_intra_pred.i: geometry_intra_pred.cpp.i

.PHONY : geometry_intra_pred.i

# target to preprocess a source file
geometry_intra_pred.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_intra_pred.cpp.i
.PHONY : geometry_intra_pred.cpp.i

geometry_intra_pred.s: geometry_intra_pred.cpp.s

.PHONY : geometry_intra_pred.s

# target to generate assembly for a file
geometry_intra_pred.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_intra_pred.cpp.s
.PHONY : geometry_intra_pred.cpp.s

geometry_octree.o: geometry_octree.cpp.o

.PHONY : geometry_octree.o

# target to build an object file
geometry_octree.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_octree.cpp.o
.PHONY : geometry_octree.cpp.o

geometry_octree.i: geometry_octree.cpp.i

.PHONY : geometry_octree.i

# target to preprocess a source file
geometry_octree.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_octree.cpp.i
.PHONY : geometry_octree.cpp.i

geometry_octree.s: geometry_octree.cpp.s

.PHONY : geometry_octree.s

# target to generate assembly for a file
geometry_octree.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_octree.cpp.s
.PHONY : geometry_octree.cpp.s

geometry_octree_decoder.o: geometry_octree_decoder.cpp.o

.PHONY : geometry_octree_decoder.o

# target to build an object file
geometry_octree_decoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_octree_decoder.cpp.o
.PHONY : geometry_octree_decoder.cpp.o

geometry_octree_decoder.i: geometry_octree_decoder.cpp.i

.PHONY : geometry_octree_decoder.i

# target to preprocess a source file
geometry_octree_decoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_octree_decoder.cpp.i
.PHONY : geometry_octree_decoder.cpp.i

geometry_octree_decoder.s: geometry_octree_decoder.cpp.s

.PHONY : geometry_octree_decoder.s

# target to generate assembly for a file
geometry_octree_decoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_octree_decoder.cpp.s
.PHONY : geometry_octree_decoder.cpp.s

geometry_octree_encoder.o: geometry_octree_encoder.cpp.o

.PHONY : geometry_octree_encoder.o

# target to build an object file
geometry_octree_encoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_octree_encoder.cpp.o
.PHONY : geometry_octree_encoder.cpp.o

geometry_octree_encoder.i: geometry_octree_encoder.cpp.i

.PHONY : geometry_octree_encoder.i

# target to preprocess a source file
geometry_octree_encoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_octree_encoder.cpp.i
.PHONY : geometry_octree_encoder.cpp.i

geometry_octree_encoder.s: geometry_octree_encoder.cpp.s

.PHONY : geometry_octree_encoder.s

# target to generate assembly for a file
geometry_octree_encoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_octree_encoder.cpp.s
.PHONY : geometry_octree_encoder.cpp.s

geometry_predictive_decoder.o: geometry_predictive_decoder.cpp.o

.PHONY : geometry_predictive_decoder.o

# target to build an object file
geometry_predictive_decoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_predictive_decoder.cpp.o
.PHONY : geometry_predictive_decoder.cpp.o

geometry_predictive_decoder.i: geometry_predictive_decoder.cpp.i

.PHONY : geometry_predictive_decoder.i

# target to preprocess a source file
geometry_predictive_decoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_predictive_decoder.cpp.i
.PHONY : geometry_predictive_decoder.cpp.i

geometry_predictive_decoder.s: geometry_predictive_decoder.cpp.s

.PHONY : geometry_predictive_decoder.s

# target to generate assembly for a file
geometry_predictive_decoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_predictive_decoder.cpp.s
.PHONY : geometry_predictive_decoder.cpp.s

geometry_predictive_encoder.o: geometry_predictive_encoder.cpp.o

.PHONY : geometry_predictive_encoder.o

# target to build an object file
geometry_predictive_encoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_predictive_encoder.cpp.o
.PHONY : geometry_predictive_encoder.cpp.o

geometry_predictive_encoder.i: geometry_predictive_encoder.cpp.i

.PHONY : geometry_predictive_encoder.i

# target to preprocess a source file
geometry_predictive_encoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_predictive_encoder.cpp.i
.PHONY : geometry_predictive_encoder.cpp.i

geometry_predictive_encoder.s: geometry_predictive_encoder.cpp.s

.PHONY : geometry_predictive_encoder.s

# target to generate assembly for a file
geometry_predictive_encoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_predictive_encoder.cpp.s
.PHONY : geometry_predictive_encoder.cpp.s

geometry_trisoup_decoder.o: geometry_trisoup_decoder.cpp.o

.PHONY : geometry_trisoup_decoder.o

# target to build an object file
geometry_trisoup_decoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_trisoup_decoder.cpp.o
.PHONY : geometry_trisoup_decoder.cpp.o

geometry_trisoup_decoder.i: geometry_trisoup_decoder.cpp.i

.PHONY : geometry_trisoup_decoder.i

# target to preprocess a source file
geometry_trisoup_decoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_trisoup_decoder.cpp.i
.PHONY : geometry_trisoup_decoder.cpp.i

geometry_trisoup_decoder.s: geometry_trisoup_decoder.cpp.s

.PHONY : geometry_trisoup_decoder.s

# target to generate assembly for a file
geometry_trisoup_decoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_trisoup_decoder.cpp.s
.PHONY : geometry_trisoup_decoder.cpp.s

geometry_trisoup_encoder.o: geometry_trisoup_encoder.cpp.o

.PHONY : geometry_trisoup_encoder.o

# target to build an object file
geometry_trisoup_encoder.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_trisoup_encoder.cpp.o
.PHONY : geometry_trisoup_encoder.cpp.o

geometry_trisoup_encoder.i: geometry_trisoup_encoder.cpp.i

.PHONY : geometry_trisoup_encoder.i

# target to preprocess a source file
geometry_trisoup_encoder.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_trisoup_encoder.cpp.i
.PHONY : geometry_trisoup_encoder.cpp.i

geometry_trisoup_encoder.s: geometry_trisoup_encoder.cpp.s

.PHONY : geometry_trisoup_encoder.s

# target to generate assembly for a file
geometry_trisoup_encoder.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/geometry_trisoup_encoder.cpp.s
.PHONY : geometry_trisoup_encoder.cpp.s

io_hls.o: io_hls.cpp.o

.PHONY : io_hls.o

# target to build an object file
io_hls.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/io_hls.cpp.o
.PHONY : io_hls.cpp.o

io_hls.i: io_hls.cpp.i

.PHONY : io_hls.i

# target to preprocess a source file
io_hls.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/io_hls.cpp.i
.PHONY : io_hls.cpp.i

io_hls.s: io_hls.cpp.s

.PHONY : io_hls.s

# target to generate assembly for a file
io_hls.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/io_hls.cpp.s
.PHONY : io_hls.cpp.s

io_tlv.o: io_tlv.cpp.o

.PHONY : io_tlv.o

# target to build an object file
io_tlv.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/io_tlv.cpp.o
.PHONY : io_tlv.cpp.o

io_tlv.i: io_tlv.cpp.i

.PHONY : io_tlv.i

# target to preprocess a source file
io_tlv.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/io_tlv.cpp.i
.PHONY : io_tlv.cpp.i

io_tlv.s: io_tlv.cpp.s

.PHONY : io_tlv.s

# target to generate assembly for a file
io_tlv.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/io_tlv.cpp.s
.PHONY : io_tlv.cpp.s

misc.o: misc.cpp.o

.PHONY : misc.o

# target to build an object file
misc.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/misc.cpp.o
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/misc.cpp.o
.PHONY : misc.cpp.o

misc.i: misc.cpp.i

.PHONY : misc.i

# target to preprocess a source file
misc.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/misc.cpp.i
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/misc.cpp.i
.PHONY : misc.cpp.i

misc.s: misc.cpp.s

.PHONY : misc.s

# target to generate assembly for a file
misc.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/misc.cpp.s
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/misc.cpp.s
.PHONY : misc.cpp.s

osspecific.o: osspecific.cpp.o

.PHONY : osspecific.o

# target to build an object file
osspecific.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/osspecific.cpp.o
.PHONY : osspecific.cpp.o

osspecific.i: osspecific.cpp.i

.PHONY : osspecific.i

# target to preprocess a source file
osspecific.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/osspecific.cpp.i
.PHONY : osspecific.cpp.i

osspecific.s: osspecific.cpp.s

.PHONY : osspecific.s

# target to generate assembly for a file
osspecific.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/osspecific.cpp.s
.PHONY : osspecific.cpp.s

partitioning.o: partitioning.cpp.o

.PHONY : partitioning.o

# target to build an object file
partitioning.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/partitioning.cpp.o
.PHONY : partitioning.cpp.o

partitioning.i: partitioning.cpp.i

.PHONY : partitioning.i

# target to preprocess a source file
partitioning.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/partitioning.cpp.i
.PHONY : partitioning.cpp.i

partitioning.s: partitioning.cpp.s

.PHONY : partitioning.s

# target to generate assembly for a file
partitioning.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/partitioning.cpp.s
.PHONY : partitioning.cpp.s

pcc_chrono.o: pcc_chrono.cpp.o

.PHONY : pcc_chrono.o

# target to build an object file
pcc_chrono.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/pcc_chrono.cpp.o
.PHONY : pcc_chrono.cpp.o

pcc_chrono.i: pcc_chrono.cpp.i

.PHONY : pcc_chrono.i

# target to preprocess a source file
pcc_chrono.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/pcc_chrono.cpp.i
.PHONY : pcc_chrono.cpp.i

pcc_chrono.s: pcc_chrono.cpp.s

.PHONY : pcc_chrono.s

# target to generate assembly for a file
pcc_chrono.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/pcc_chrono.cpp.s
.PHONY : pcc_chrono.cpp.s

ply.o: ply.cpp.o

.PHONY : ply.o

# target to build an object file
ply.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/ply.cpp.o
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/ply.cpp.o
.PHONY : ply.cpp.o

ply.i: ply.cpp.i

.PHONY : ply.i

# target to preprocess a source file
ply.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/ply.cpp.i
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/ply.cpp.i
.PHONY : ply.cpp.i

ply.s: ply.cpp.s

.PHONY : ply.s

# target to generate assembly for a file
ply.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/ply.cpp.s
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/ply.cpp.s
.PHONY : ply.cpp.s

pointset_processing.o: pointset_processing.cpp.o

.PHONY : pointset_processing.o

# target to build an object file
pointset_processing.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/pointset_processing.cpp.o
.PHONY : pointset_processing.cpp.o

pointset_processing.i: pointset_processing.cpp.i

.PHONY : pointset_processing.i

# target to preprocess a source file
pointset_processing.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/pointset_processing.cpp.i
.PHONY : pointset_processing.cpp.i

pointset_processing.s: pointset_processing.cpp.s

.PHONY : pointset_processing.s

# target to generate assembly for a file
pointset_processing.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/pointset_processing.cpp.s
.PHONY : pointset_processing.cpp.s

quantization.o: quantization.cpp.o

.PHONY : quantization.o

# target to build an object file
quantization.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/quantization.cpp.o
.PHONY : quantization.cpp.o

quantization.i: quantization.cpp.i

.PHONY : quantization.i

# target to preprocess a source file
quantization.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/quantization.cpp.i
.PHONY : quantization.cpp.i

quantization.s: quantization.cpp.s

.PHONY : quantization.s

# target to generate assembly for a file
quantization.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/quantization.cpp.s
.PHONY : quantization.cpp.s

tables.o: tables.cpp.o

.PHONY : tables.o

# target to build an object file
tables.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/tables.cpp.o
.PHONY : tables.cpp.o

tables.i: tables.cpp.i

.PHONY : tables.i

# target to preprocess a source file
tables.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/tables.cpp.i
.PHONY : tables.cpp.i

tables.s: tables.cpp.s

.PHONY : tables.s

# target to generate assembly for a file
tables.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/tables.cpp.s
.PHONY : tables.cpp.s

version.o: version.cpp.o

.PHONY : version.o

# target to build an object file
version.cpp.o:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/version.cpp.o
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/version.cpp.o
.PHONY : version.cpp.o

version.i: version.cpp.i

.PHONY : version.i

# target to preprocess a source file
version.cpp.i:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/version.cpp.i
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/version.cpp.i
.PHONY : version.cpp.i

version.s: version.cpp.s

.PHONY : version.s

# target to generate assembly for a file
version.cpp.s:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/ply-merge.dir/build.make tmc3/CMakeFiles/ply-merge.dir/version.cpp.s
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(MAKE) -f tmc3/CMakeFiles/tmc3.dir/build.make tmc3/CMakeFiles/tmc3.dir/version.cpp.s
.PHONY : version.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ply-merge"
	@echo "... tmc3"
	@echo "... install/strip"
	@echo "... genversion"
	@echo "... AttributeCommon.o"
	@echo "... AttributeCommon.i"
	@echo "... AttributeCommon.s"
	@echo "... AttributeDecoder.o"
	@echo "... AttributeDecoder.i"
	@echo "... AttributeDecoder.s"
	@echo "... AttributeEncoder.o"
	@echo "... AttributeEncoder.i"
	@echo "... AttributeEncoder.s"
	@echo "... DualLutCoder.o"
	@echo "... DualLutCoder.i"
	@echo "... DualLutCoder.s"
	@echo "... FixedPoint.o"
	@echo "... FixedPoint.i"
	@echo "... FixedPoint.s"
	@echo "... OctreeNeighMap.o"
	@echo "... OctreeNeighMap.i"
	@echo "... OctreeNeighMap.s"
	@echo "... RAHT.o"
	@echo "... RAHT.i"
	@echo "... RAHT.s"
	@echo "... TMC3.o"
	@echo "... TMC3.i"
	@echo "... TMC3.s"
	@echo "... __/dependencies/program-options-lite/program_options_lite.o"
	@echo "... __/dependencies/program-options-lite/program_options_lite.i"
	@echo "... __/dependencies/program-options-lite/program_options_lite.s"
	@echo "... __/dependencies/schroedinger/schroarith.o"
	@echo "... __/dependencies/schroedinger/schroarith.i"
	@echo "... __/dependencies/schroedinger/schroarith.s"
	@echo "... __/tools/ply-merge.o"
	@echo "... __/tools/ply-merge.i"
	@echo "... __/tools/ply-merge.s"
	@echo "... attribute_raw_decoder.o"
	@echo "... attribute_raw_decoder.i"
	@echo "... attribute_raw_decoder.s"
	@echo "... attribute_raw_encoder.o"
	@echo "... attribute_raw_encoder.i"
	@echo "... attribute_raw_encoder.s"
	@echo "... coordinate_conversion.o"
	@echo "... coordinate_conversion.i"
	@echo "... coordinate_conversion.s"
	@echo "... decoder.o"
	@echo "... decoder.i"
	@echo "... decoder.s"
	@echo "... encoder.o"
	@echo "... encoder.i"
	@echo "... encoder.s"
	@echo "... entropydirac.o"
	@echo "... entropydirac.i"
	@echo "... entropydirac.s"
	@echo "... frame.o"
	@echo "... frame.i"
	@echo "... frame.s"
	@echo "... geometry_intra_pred.o"
	@echo "... geometry_intra_pred.i"
	@echo "... geometry_intra_pred.s"
	@echo "... geometry_octree.o"
	@echo "... geometry_octree.i"
	@echo "... geometry_octree.s"
	@echo "... geometry_octree_decoder.o"
	@echo "... geometry_octree_decoder.i"
	@echo "... geometry_octree_decoder.s"
	@echo "... geometry_octree_encoder.o"
	@echo "... geometry_octree_encoder.i"
	@echo "... geometry_octree_encoder.s"
	@echo "... geometry_predictive_decoder.o"
	@echo "... geometry_predictive_decoder.i"
	@echo "... geometry_predictive_decoder.s"
	@echo "... geometry_predictive_encoder.o"
	@echo "... geometry_predictive_encoder.i"
	@echo "... geometry_predictive_encoder.s"
	@echo "... geometry_trisoup_decoder.o"
	@echo "... geometry_trisoup_decoder.i"
	@echo "... geometry_trisoup_decoder.s"
	@echo "... geometry_trisoup_encoder.o"
	@echo "... geometry_trisoup_encoder.i"
	@echo "... geometry_trisoup_encoder.s"
	@echo "... io_hls.o"
	@echo "... io_hls.i"
	@echo "... io_hls.s"
	@echo "... io_tlv.o"
	@echo "... io_tlv.i"
	@echo "... io_tlv.s"
	@echo "... misc.o"
	@echo "... misc.i"
	@echo "... misc.s"
	@echo "... osspecific.o"
	@echo "... osspecific.i"
	@echo "... osspecific.s"
	@echo "... partitioning.o"
	@echo "... partitioning.i"
	@echo "... partitioning.s"
	@echo "... pcc_chrono.o"
	@echo "... pcc_chrono.i"
	@echo "... pcc_chrono.s"
	@echo "... ply.o"
	@echo "... ply.i"
	@echo "... ply.s"
	@echo "... pointset_processing.o"
	@echo "... pointset_processing.i"
	@echo "... pointset_processing.s"
	@echo "... quantization.o"
	@echo "... quantization.i"
	@echo "... quantization.s"
	@echo "... tables.o"
	@echo "... tables.i"
	@echo "... tables.s"
	@echo "... version.o"
	@echo "... version.i"
	@echo "... version.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd "/media/jiaby/My Passport/Liugexin/mpeg-pcc-tmc13-master/build" && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

